trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # Build and push Docker image
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/CHAP09/appdocker/Dockerfile'
        tags: |
          $(tag)
    
    # Terraform deploy
    - task: Bash@3
      displayName: Deploy with Terraform
      inputs:
        targetType: 'inline'
        workingDirectory: 'CHAP09/terraform-aci'
        script: |
          export ARM_CLIENT_ID="${ARM_CLIENT_ID}"
          export ARM_CLIENT_SECRET="${ARM_CLIENT_SECRET}"
          export ARM_SUBSCRIPTION_ID="${ARM_SUBSCRIPTION_ID}"
          export ARM_TENANT_ID="${ARM_TENANT_ID}"
          
          # Initialize Terraform with backend configuration
          terraform init -backend-config="backend.tvars"
          
          # Apply Terraform with variables for Docker image version and username
          terraform apply \
            -var "imageversion=$(Build.BuildNumber)" \
            -var "dockerhub-username=$(dockerhub_username)" \
            --auto-approve
